# safe_rsync 設定ファイル。
# 行頭に#がある行はコメント行です。

# rsync元

Home="/home/nyj94/nyj94.xsrv.jp/safe_rsync"
Source="$Home/source/"

# デフォルトの除外指定ファイル
DefaultExcludeFile="$Home/exclude_pattern"

#反映先(実WEBファイル)
Destination="/home/nyj94/nyj94.xsrv.jp/cms-app"


# rsyncのオプション
# rsyncOption       = "--update -rlptvz --delete"
#rsyncOption       = "-rlptv --no-p --no-o --delete --cvs-exclude --keep-dirlinks"
##rsyncOption        = "--checksum -rlptv --no-p --no-o --delete --cvs-exclude --keep-dirlinks -O"
##削除(delete)なし
rsyncOption        = "--checksum -rlptv --no-p --no-o --cvs-exclude --keep-dirlinks -O"

#以下のコマンドではfile_list.txtに記載したファイルのみを対象とする
#rsyncOption        = "--checksum --files-from='/home/petabit-user/safe_rsync/file_list.txt' -rlptv --no-p --no-o --cvs-exclude --keep-dirlinks -O"


# ログファイル保存先
LogFileDirectory   = "$Home/logs"

# ログファイル名に付けられるタイムスタンプ(see 'man date')
LogFileTimeStamp   = "+%Y%m%d_%Hh%Mm%Ss"`
# ログファイル名
# RsyncLogFile       = "rsync"
# 未実行ログファイル名
# DonotRsyncLogFile  = "donotrsync"

# rsync バックアップオプション
rsyncBackupOption = "--backup --backup-dir=$Home/backup"


RsyncLogFile="rsync_"
DonotRsyncLogFile="donotrsync_"

Version="1.0.1"

ConfFile="safe_rsync.conf"
#
TEMPFILEDIR="/tmp/`basename $0`_`date +%F_%T`"
#
EXCLUDEFILE="$TEMPFILEDIR/exclude_pattern"
#
DRYRUNFILE="$TEMPFILEDIR/dryrun.tmp"
TMPFILE="$TEMPFILEDIR/tmp.tmp"
HIGHLIGHTCOLOR="\033[33m"
NORMCOLOR="\033[0m"
PAGERMODE=1

# 実行するrsync
rsync              = "/usr/bin/rsync"

RSYNC_MAILTO=""
