name: Main Config
version: 1.0.0
schema: v1
models:
 - name: qwen2.5-coder:14b 
 ##- name: qwen3-coder:30b
 ## - name: qwen3.6:27b
   provider: ollama
   model: qwen2.5-coder:14b 
  ## model: qwen3-coder:30b
  ##  model: qwen3.6:27b
   roles:
      - chat
      - edit
      - apply
 - name: qwen2.5-coder:1.5b-base
   provider: ollama
   model: qwen2.5-coder:1.5b-base
   roles:
      - autocomplete
 - name: Nomic Embed
   provider: ollama
   model: nomic-embed-text:latest
   roles:
      - embed

